import { Todo } from "@/types";

export const tasksJson: Todo[] =  [{
    "id": 1,
    "havedoit": null,
    "name": "Planifier la réunion d'équipe",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_time": "09:00:00",
    "end_time": "10:00:00",
    "start_date": "2025-07-22",
    "deadline": "2025-07-25",
    "type": 'habit',
    "start_at": "2025-07-22",
    "finish_at": "2025-07-25",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 1,
    "havedoit": null,
    "name": "je vais en balade",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_time": "05:00:00",
    "end_time": "09:00:00",
    "start_date": "2025-07-24",
    "deadline": "2025-07-24",
    "type": 'task',
    "start_at": "2025-07-24",
    "finish_at": "2025-07-24",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 1,
    "havedoit": null,
    "name": "faire la priere",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_time": "03:00:00",
    "end_time": "05:00:00",
    "start_date": "2025-07-20",
    "deadline": "2025-07-28",
    "type": 'habit',
    "start_at": "2025-07-20",
    "finish_at": "2025-07-28",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 2,
    "havedoit": null,
    "name": "Rédiger le rapport mensuel",
    "taskable_id": 201,
    "taskable_type": "Report",
    "state": "not started",
    "priority": "high",
    "description": "Collecter les données et analyser les performances du mois.",
    "start_time": '01:00:00',
    "end_time": "03:00:00",
    "start_date": "2025-07-24",
    "deadline": "2025-07-31",
    "type": 'habit',
    "start_at": "2025-07-24",
    "finish_at": "2025-07-32",
    "author": "Bob",
    "created_at": "2025-07-21T14:00:00Z",
    "updated_at": "2025-07-21T14:00:00Z"
  },
  {
    "id": 3,
    "name": "Mettre à jour le site web",
    "taskable_id": "product-page-update",
    "taskable_type": "WebsiteSection",
    "state": "paused",
    "priority": "medium",
    "description": "Ajouter de nouvelles fonctionnalités et corriger les bugs mineurs.",
    "start_time": "11:00:00",
    "end_time": "13:00:00",
    "start_date": "2025-07-15",
    "deadline": "2025-08-01",
    "type": 'habit',
    'havedoit': ['2025-07-23', '2025-07-23', '2025-07-21', '2025-07-2024'],
    "start_at": "2025-07-15",
    "finish_at": "2025-07-31",
    "author": "Charlie",
    "created_at": "2025-07-10T10:00:00Z",
    "updated_at": "2025-07-18T16:00:00Z"
  },
  {
    "id": 4,
    "havedoit": null,
    "name": "Répondre aux e-mails clients",
    "taskable_id": 305,
    "taskable_type": "SupportTicket",
    "state": "in progress",
    "priority": "low",
    "description": '',
    "start_time": "08:30:00",
    "end_time": '10:00:00',
    "start_date": "2025-07-23",
    "deadline": "2025-07-23",
    "type": 'task',
    "start_at": "2025-07-23",
    "finish_at": "2025-07-31",
    "author": "Diana",
    "created_at": "2025-07-23T08:00:00Z",
    "updated_at": "2025-07-23T09:00:00Z"
  },
  {
    "id": 5,
    "havedoit": null,
    "name": "Préparer la présentation",
    "taskable_id": 401,
    "taskable_type": "Meeting",
    "state": "done",
    "priority": "high",
    "description": "Finaliser les diapositives pour la présentation du Q3.",
    "start_time": "14:00:00",
    "end_time": "16:00:00",
    "start_date": "2025-07-19",
    "deadline": "2025-07-19",
    "type": 'task',
    "start_at": "2025-07-19",
    "finish_at": "2025-07-22",
    "author": "Eve",
    "created_at": "2025-07-18T09:00:00Z",
    "updated_at": "2025-07-22T16:30:00Z"
  },
  {
    "id": 6,
    "havedoit": null,
    "name": "Former les nouveaux employés",
    "taskable_id": "onboarding-batch-5",
    "taskable_type": "HRTraining",
    "state": "in progress",
    "priority": "medium",
    "description": "Sessions de formation sur les outils internes.",
    "start_time": "10:00:00",
    "end_time": "12:00:00",
    "start_date": "2025-07-22",
    "deadline": "2025-07-22",
    "type": 'task',
    "start_at": "2025-07-22",
    "finish_at": "2025-07-22",
    "author": "Frank",
    "created_at": "2025-07-20T11:00:00Z",
    "updated_at": "2025-07-22T11:30:00Z"
  },
  {
    "id": 7,
    "havedoit": null,
    "name": "Analyser les données de vente",
    "taskable_id": 502,
    "taskable_type": "DataAnalysis",
    "state": "not started",
    "priority": "high",
    "description": "Évaluer les tendances de vente du dernier trimestre.",
    "start_time": '04:00:00',
    "end_time": '10:00:00',
    "start_date": "2025-07-25",
    "deadline": "2025-07-25",
    "type": 'task',
    "start_at": "2025-07-25",
    "finish_at": "2025-07-25",
    "author": "Grace",
    "created_at": "2025-07-22T15:00:00Z",
    "updated_at": "2025-07-22T15:00:00Z"
  },
  {
    "id": 8,
    "havedoit": null,
    "name": "Organiser l'événement d'entreprise",
    "taskable_id": "annual-gala-2025",
    "taskable_type": "Event",
    "state": "canceled",
    "priority": "medium",
    "description": "Réservation du lieu, traiteur, divertissements.",
    "start_time": '03:00:00',
    "end_time": '07:00:00',
    "start_date": "2025-07-26",
    "deadline": "2025-07-26",
    "type": 'task',
    "start_at": "2025-06-01T09:00:00Z",
    "finish_at": "2025-07-26",
    "author": "Heidi",
    "created_at": "2025-05-28T10:00:00Z",
    "updated_at": "2025-07-10T11:00:00Z"
  },
  {
    "id": 9,
    "havedoit": null,
    "name": "Revoir les politiques de sécurité",
    "taskable_id": 601,
    "taskable_type": "PolicyReview",
    "state": "in progress",
    "priority": "high",
    "description": "Assurer la conformité avec les nouvelles réglementations.",
    "start_time": "13:00:00",
    "end_time": "15:00:00",
    "start_date": "2025-07-23",
    "deadline": "2025-07-23",
    "type": 'task',
    "start_at": "2025-07-23T13:00:00Z",
    "finish_at": "2025-07-26",
    "author": "Ivy",
    "created_at": "2025-07-21T09:00:00Z",
    "updated_at": "2025-07-23T13:00:00Z"
  },
  {
    "id": 10,
    "havedoit": null,
    "name": "Tester la nouvelle version du logiciel",
    "taskable_id": "v2.1-release",
    "taskable_type": "SoftwareRelease",
    "state": "done",
    "priority": "medium",
    "description": "Effectuer des tests de régression et des tests fonctionnels.",
    "start_time": "09:00:00",
    "end_time": "17:00:00",
    "start_date": "2025-07-15",
    "deadline": "2025-07-15",
    "type": 'task',
    "start_at": "2025-07-15",
    "finish_at": "2025-07-22",
    "author": "Jack",
    "created_at": "2025-07-14T10:00:00Z",
    "updated_at": "2025-07-22T17:00:00Z"
  }]

export const tasksTeamJson: Todo[] = [
  {
    "id": 1,
    "havedoit": null,
    "name": "Planifier la réunion d'équipe",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_date": "2025-07-22",
    "deadline": "2025-07-25",
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "type": 'habit',
    "start_at": "2025-07-22",
    "finish_at": "2025-07-25",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 1,
    "name": "je vais en balade",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_date": "2025-07-24",
    "deadline": "2025-07-24",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-24",
    "finish_at": "2025-07-24",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 1,
    "name": "faire la priere",
    "taskable_id": 101,
    "taskable_type": "Project",
    "state": "in progress",
    "priority": "high",
    "description": "Préparer l'ordre du jour et inviter les participants.",
    "start_date": "2025-07-20",
    "deadline": "2025-07-28",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-20",
    "finish_at": "2025-07-28",
    "author": "Alice",
    "created_at": "2025-07-20T10:00:00Z",
    "updated_at": "2025-07-22T09:30:00Z"
  },
  {
    "id": 2,
    "name": "Rédiger le rapport mensuel",
    "taskable_id": 201,
    "taskable_type": "Report",
    "state": "not started",
    "priority": "high",
    "description": "Collecter les données et analyser les performances du mois.",
    "start_date": "2025-07-24",
    "deadline": "2025-07-31",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-24",
    "finish_at": "2025-07-32",
    "author": "Bob",
    "created_at": "2025-07-21T14:00:00Z",
    "updated_at": "2025-07-21T14:00:00Z"
  },
  {
    "id": 3,
    "name": "Mettre à jour le site web",
    "taskable_id": "product-page-update",
    "taskable_type": "WebsiteSection",
    "state": "paused",
    "priority": "medium",
    "description": "Ajouter de nouvelles fonctionnalités et corriger les bugs mineurs.",
    "start_date": "2025-07-15",
    "deadline": "2025-08-01",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-15",
    "finish_at": "2025-07-31",
    "author": "Charlie",
    "created_at": "2025-07-10T10:00:00Z",
    "updated_at": "2025-07-18T16:00:00Z"
  },
  {
    "id": 4,
    "name": "Répondre aux e-mails clients",
    "taskable_id": 305,
    "taskable_type": "SupportTicket",
    "state": "in progress",
    "priority": "low",
    "description": '',
    "start_date": "2025-07-23",
    "deadline": "2025-07-23",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-23",
    "finish_at": "2025-07-31",
    "author": "Diana",
    "created_at": "2025-07-23T08:00:00Z",
    "updated_at": "2025-07-23T09:00:00Z"
  },
  {
    "id": 5,
    "name": "Préparer la présentation",
    "taskable_id": 401,
    "taskable_type": "Meeting",
    "state": "done",
    "priority": "high",
    "description": "Finaliser les diapositives pour la présentation du Q3.",
    "start_date": "2025-07-19",
    "deadline": "2025-07-19",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-19",
    "finish_at": "2025-07-22",
    "author": "Eve",
    "created_at": "2025-07-18T09:00:00Z",
    "updated_at": "2025-07-22T16:30:00Z"
  },
  {
    "id": 6,
    "name": "Former les nouveaux employés",
    "taskable_id": "onboarding-batch-5",
    "taskable_type": "HRTraining",
    "state": "in progress",
    "priority": "medium",
    "description": "Sessions de formation sur les outils internes.",
    "start_date": "2025-07-22",
    "deadline": "2025-07-22",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-22",
    "finish_at": "2025-07-22",
    "author": "Frank",
    "created_at": "2025-07-20T11:00:00Z",
    "updated_at": "2025-07-22T11:30:00Z"
  },
  {
    "id": 7,
    "name": "Analyser les données de vente",
    "taskable_id": 502,
    "taskable_type": "DataAnalysis",
    "state": "not started",
    "priority": "high",
    "description": "Évaluer les tendances de vente du dernier trimestre.",
    "start_date": "2025-07-25",
    "deadline": "2025-07-25",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-25",
    "finish_at": "2025-07-25",
    "author": "Grace",
    "created_at": "2025-07-22T15:00:00Z",
    "updated_at": "2025-07-22T15:00:00Z"
  },
  {
    "id": 8,
    "name": "Organiser l'événement d'entreprise",
    "taskable_id": "annual-gala-2025",
    "taskable_type": "Event",
    "state": "canceled",
    "priority": "medium",
    "description": "Réservation du lieu, traiteur, divertissements.",
    "start_date": "2025-07-26",
    "deadline": "2025-07-26",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-06-01T09:00:00Z",
    "finish_at": "2025-07-26",
    "author": "Heidi",
    "created_at": "2025-05-28T10:00:00Z",
    "updated_at": "2025-07-10T11:00:00Z"
  },
  {
    "id": 9,
    "name": "Revoir les politiques de sécurité",
    "taskable_id": 601,
    "taskable_type": "PolicyReview",
    "state": "in progress",
    "priority": "high",
    "description": "Assurer la conformité avec les nouvelles réglementations.",
    "start_date": "2025-07-23",
    "deadline": "2025-07-23",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-23T13:00:00Z",
    "finish_at": "2025-07-26",
    "author": "Ivy",
    "created_at": "2025-07-21T09:00:00Z",
    "updated_at": "2025-07-23T13:00:00Z"
  },
  {
    "id": 10,
    "name": "Tester la nouvelle version du logiciel",
    "taskable_id": "v2.1-release",
    "taskable_type": "SoftwareRelease",
    "state": "done",
    "priority": "medium",
    "description": "Effectuer des tests de régression et des tests fonctionnels.",
    "start_date": "2025-07-15",
    "deadline": "2025-07-15",
    "type": 'task',
    "assigned": [ 'marcdeus@gmail.com',"austinndjom@gmail.com",],
    "start_at": "2025-07-15",
    "finish_at": "2025-07-22",
    "author": "Jack",
    "created_at": "2025-07-14T10:00:00Z",
    "updated_at": "2025-07-22T17:00:00Z"
  }

]

export const meetingsTeamJson = [
  {
    id: 0,
    name: 'team standup',
    topics: 'standup',
    description: 'je ne sais pas vraiment hein, tous ce que je peux dire c que je ne connais pas ce que standup vx dire',
    schedule_at: '2025-07-22',
    start_time: '19:00:00',
    author: "alice"
  },
  {
    id: 0,
    name: 'team weekly',
    topics: 'team weekly',
    description: 'je ne sais pas vraiment hein, tous ce que je peux dire c que je ne connais pas ce que standup vx dire',
    schedule_at: '2025-06-01',
    start_time: '15:00:00',
    author: "Bob"
  },
  {
    id: 0,
    name: 'getting started with meetings notes',
    topics: 'training',
    description: 'je ne sais pas vraiment hein, tous ce que je peux dire c que je ne connais pas ce que standup vx dire',
    schedule_at: '2025-07-14',
    start_time: '08:00:00',
    author: "Bob"
  }
]

export const messageJson = [
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    salutation: 'Hello thierry',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    salutation: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    salutation: 'Hello thierry',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    salutation: 'Hello thierry',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    is_read: false,
    salutation: 'Hello thierry',
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    send_at: '2020-05-08',
    salutation: 'Hello thierry',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  },
  {
    id: 0,
    sender_id: 1,
    receiver_id: 2,
    subject: 'Projects onboarding',
    greeting: 'Hello thierry',
    closing: 'Good bye',
    salutation: 'Hello thierry',
    send_at: '2020-05-08',
    is_read: false,
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis. >Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint assumenda doloribus minus molestias quasi! Reiciendis, amet voluptatem voluptas eius error distinctio dignissimos mollitia labore, animi commodi odit sint quae quis.',
  }
  
]

export const teamsJson = [
  {
    name: 'Front End',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae odit dolore nulla nemo qui ratione provident culpa debitis, veniam eos blanditiis quaerat exercitationem facere aliquid consequuntur modi, fugiat temporibus?',
    mission: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae odit dolore nulla nemo qui ratione provident culpa debitis, veniam eos blanditiis quaerat exercitationem facere aliquid consequuntur modi, fugiat temporibus?',
    author: 'marc devus',
    create_at: '2020-05-18'
  }
]